dataloader:
  module_path: nowcasting.data.dataloader_zarrv3.NowcastingDataModule
  path: "/vol/knmimo-nobackup/users/mrobben/nowcasting/data/dataset_regrid.zarr"
  var_info:
    sample_var: "radar/max_intensity_grid"
    in_vars:
      - "radar/rtcor"
    out_vars:
      - "radar/rtcor"
    transforms: 
      radar: 
        dbz_normalization:
          convert_to_dbz: true

  split_info:
    split_rules:
      test:
        year: 
        - 2023
      val:
        month:
          - 6
          - 11
      train: {}
    apply_missing_masks:
      - "radar"
      - "harmonie"
      - "sat_l2"
      - "sat_l1p5"
      - "aws"
    clutter_threshold: 50

  sample_info:
    # bins:
    #   n_bins: 30
    #   first_bin: 0.02
    #   last_bin: 30.0
    #   slope: 0.2
    #   scaler: 5.1 # 255/50
    #   n_samples: 30000
    threshold: 0.01
    methods:
      train:
        agg: "mean_pool"
      val:
        agg: "mean_pool"
        center_crop: true
      test:
        agg: "mean_pool"

  context_len: 4
  forecast_len: 18
  img_size: [8, 8]
  stride: [1,1,1]
  batch_size: 8
  num_workers: 12
trainer:
  max_epochs: 500
  accelerator: "auto"
  strategy: "ddp_find_unused_parameters_true"
  precision: "16-mixed"
  profiler: "simple"
  limit_train_batches: 1000
  # limit_val_batches: 20
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  accumulate_grad_batches: 1
logger:
  save_dir: "./results/tb_logs"
  name: "earthformer"
callbacks:
  checkpoint:
    monitor: "val/loss"
    save_top_k: 1
    save_last: true
    mode: "min"
  early_stopping:
    monitor: "val/loss"
    min_delta: 0.0
    patience: 5
    verbose: true
    mode: "min"
optimizer:
  method: "adamw"
  lr: 0.0001
  weight_decay: 0.0
  # scheduler
  lr_scheduler_mode: null
  min_lr_ratio: 1.0e-3
  warmup_min_lr_ratio: 0.0
  warmup_percentage: 0.2

model:
  module_path: nowcasting.models.earthformer.earthformer.CuboidSEVIRPLModule
  checkpoint_path: null
  input_shape: [4, 256, 256, 1]
  target_shape: [18, 256, 256, 1]
  base_units: 128
  block_units: null
  scale_alpha: 1.0

  enc_depth: [1, 1]
  dec_depth: [1, 1]
  enc_use_inter_ffn: true
  dec_use_inter_ffn: true
  dec_hierarchical_pos_embed: false

  downsample: 2
  downsample_type: "patch_merge"
  upsample_type: "upsample"

  num_global_vectors: 8
  use_dec_self_global: false
  dec_self_update_global: true
  use_dec_cross_global: false
  use_global_vector_ffn: false
  use_global_self_attn: true
  separate_global_qkv: true
  global_dim_ratio: 1

  # self_pattern: "axial"
  enc_attn_patterns: "axial"
  # cross_self_pattern: "axial"
  dec_self_attn_patterns: "axial"
  # cross_pattern: "cross_1x1"
  dec_cross_attn_patterns: "cross_1x1"
  dec_cross_last_n_frames: null

  attn_drop: 0.1
  proj_drop: 0.1
  ffn_drop: 0.1
  num_heads: 4

  ffn_activation: "gelu"
  gated_ffn: false
  norm_layer: "layer_norm"
  padding_type: "zeros"
  pos_embed_type: "t+h+w"
  use_relative_pos: true
  self_attn_use_final_proj: true
  dec_use_first_self_attn: false

  z_init_method: "zeros"
  checkpoint_level: 0

  initial_downsample_type: "stack_conv"
  initial_downsample_activation: "leaky"
  initial_downsample_stack_conv_num_layers: 3
  initial_downsample_stack_conv_dim_list: [16, 64, 128]
  initial_downsample_stack_conv_downscale_list: [3, 2, 2]
  initial_downsample_stack_conv_num_conv_list: [2, 2, 2]

  attn_linear_init_mode: "0"
  ffn_linear_init_mode: "0"
  conv_init_mode: "0"
  down_up_linear_init_mode: "0"
  norm_init_mode: "0"
eval:
  model_name: "earthformer"
  num_samples: 32000