dataloader:
  module_path: nowcasting.data.dataloader_zarrv3.NowcastingDataModule
  path: "/vol/knmimo-nobackup/users/mrobben/nowcasting/data/dataset_regrid.zarr"
  var_info:
    sample_var: "radar/max_intensity_grid"
    latlon: false
    in_vars:
      - ["radar/rtcor"]
      - ["sat_l1p5/WV_062", "sat_l1p5/IR_108"]
    out_vars:
      - "radar/rtcor"
    transforms:
      radar: 
        dbz_normalization:
          convert_to_dbz: true

      sat_l1p5: 
        resize:
          scale: 2
      sat_l1p5/WV_062:
        normalize: {mean: 230.6474, std: 4.9752}
      sat_l1p5/IR_108:
        normalize: {mean: 266.7156, std: 16.5736}
    
  split_info:
    split_rules:
      test:
        year: 
        - 2023
      val:
        month:
          - 6
          - 11
      train: {}
    apply_missing_masks:
      - "radar"
      - "harmonie"
      - "sat_l2"
      - "sat_l1p5"
      - "aws"
    clutter_threshold: 50

  sample_info:
    threshold: 0.01
    methods:
      train:
        agg: "mean_pool"
      val:
        agg: "mean_pool"
        center_crop: true
      test:
        agg: "mean_pool"

  context_len: 4
  forecast_len: 20
  include_timestamps: true
  img_size: [4, 4]
  stride: [1,1,1]
  batch_size: 8
  num_workers: 8
trainer:
  max_epochs: 1000
  accelerator: "auto"
  strategy: "auto"
  precision: "16-mixed"
  profiler: "simple"
  limit_train_batches: 1000
  # limit_val_batches: 
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  accumulate_grad_batches: 1
logger:
  save_dir: "./results/tb_logs"
  name: "ldcast_nowcast"
loss:
  loss_name: "balanced"
  min_val: 0.0
  max_val: 55.0
  max_weight_r: 30
  weight_intensity: 1.0
  extended: true
callbacks:
  checkpoint:
    monitor: "val/loss"
    save_top_k: 3
    save_last: true
    mode: "min"
  early_stopping:
    monitor: "val/loss"
    min_delta: 0.0
    patience: 6
    verbose: true
    mode: "min"
optimizer:
  lr: 1e-3
  weight_decay: 1e-4
  betas: [0.5, 0.9]
  # scheduler
  patience: 3
  factor: 0.25
  monitor: "val/loss"
model:
  module_path: nowcasting.models.ldcast.models.nowcast.nowcast.AFNONowcastModule
  checkpoint_path: null
  compile: false
  
  # Main model parameters
  embed_dim: [128, 128]
  analysis_depth: [4, 4]
  forecast_depth: 4
  input_patches: [1, 1]
  input_size_ratios: [1, 1]
  output_patches: 5
  afno_fusion: false
  use_forecast: true
  # per_input_forecast_depth: [0]
  
  # Autoencoder configurations
  input_autoencoders:
    -  # Radar autoencoder config
      model:
        enc_params:
          in_dim: 1
          levels: 2
          min_ch: 64
        dec_params:
           in_dim: 1
           levels: 2
           min_ch: 64
        kl_weight: 0.01
        encoder_channels: 64
        hidden_width: 32
    -  # Satellite autoencoder config
      model:
        enc_params:
          in_dim: 2
          levels: 2
          min_ch: 64
        dec_params:
           in_dim: 2
           levels: 2
           min_ch: 64
        kl_weight: 0.01
        encoder_channels: 64
        hidden_width: 64
  
  # Autoencoder checkpoints
  input_autoencoder_ckpts:
    - "/vol/knmimo-nobackup/users/mrobben/nowcasting/results/tb_logs/ldcast_autoenc/version_6/checkpoints/epoch=37-step=38000.ckpt"
    - "/vol/knmimo-nobackup/users/mrobben/nowcasting/results/tb_logs/ldcast_autoenc/version_9/checkpoints/epoch=101-step=102000.ckpt"

  # Output autoencoder
  # Default: take first input_autoencoder
  
  # Freezing options
  pretrained_paths:
    - null
    - "/vol/knmimo-nobackup/users/mrobben/nowcasting/results/tb_logs/ldcast_nowcast/version_8/checkpoints/epoch=78-step=79000.ckpt"
  freeze_pretrained: [false, true]  # Freeze satellite pipeline

eval:
  model_name: "earthformer"
  num_samples: 32000