dataloader:
  module_path: nowcasting.data.dataloader_zarrv3.NowcastingDataModule
  path: "/projects/prjs1634/nowcasting/data/dataset.zarr"
  var_info:
    sample_var: "radar/max_intensity_grid"
    in_vars:
      - "radar/rtcor"
    out_vars: 
      - "radar/rtcor"
    transforms: {}
  
  split_info:
    split_rules:
      test:
        year: 
        - 2023
      val:
        month:
          - 6
          - 11
      train: {}
    apply_missing_masks:
      - "radar"
      - "harmonie"
      - "sat_l2"
      - "sat_l1p5"
      - "aws_inter"
    clutter_threshold: 50
    # convection_mask: true

  sample_info:
    threshold: 0.8
    methods:
      train:
        agg: "mean_pool"
      val:
        agg: "mean_pool"
        # center_crop: true
      test:
        agg: "mean_pool"
        # center_crop: true

  context_len: 4
  forecast_len: 18
  img_size: [24, 22]
  stride: [4,1,1]
  return_index: true
  batch_size: 8
  num_workers: 18
model:
  module_path: nowcasting.benchmarks.pysteps.PySTEPSModel
  method: "sprog"
  future_timesteps: 18
  km_per_pixel: 1.0
eval:
  model_path: nowcasting.benchmarks.pysteps.PySTEPSModel
  model_name: "sprog"
  save_dir: "/projects/prjs1634/nowcasting/results/scores"
  eval_subdir: "full_coverage"
  leadtimes: [5,10,15,30,60,90]
  thresholds: [0.5, 1, 2, 5, 10, 20, 30]
  num_samples: 100