dataloader:
  module_path: nowcasting.data.dataloader_zarrv3.NowcastingDataModule
  path: "/projects/prjs1634/nowcasting/data/dataset.zarr"
  var_info:
    sample_var: "radar/max_intensity_grid"
    latlon: false
    in_vars:
      - "radar/rtcor"
    transforms:
      radar: 
        default_rainrate: {mean: 0.03019706713265408, std: 0.5392297631902654}

  split_info:
    split_rules:
      test:
        year: 
        - 2023
      val:
        month:
          - 6
          - 11
      train: {}
    apply_missing_masks:
      - "radar"
      - "harmonie"
      - "sat_l2"
      - "sat_l1p5"
      - "aws_inter"
    clutter_threshold: 50

  sample_info:
    threshold: 0.01
    methods:
      train:
        agg: "mean_pool"
      val:
        agg: "mean_pool"
        center_crop: true
      test:
        agg: "mean_pool"

  context_len: 8
  forecast_len: 0
  img_size: [4, 4]
  stride: [4,1,1]
  batch_size: 16
  num_workers: 24
trainer:
  max_epochs: 100
  accelerator: "auto"
  strategy: "auto"
  precision: 32 #"16-mixed"
  profiler: "simple"
  limit_train_batches: 2000
  # limit_val_batches: 20
  accumulate_grad_batches: 1
logger:
  save_dir: "./results/tb_logs"
  name: "ldcast_autoenc"
callbacks:
  checkpoint:
    monitor: "val/rec_loss"
    save_top_k: 3
    save_last: true
    mode: "min"
  early_stopping:
    monitor: "val/rec_loss"
    min_delta: 0.0
    patience: 6
    verbose: true
    mode: "min"
optimizer:
  lr: 1e-4
  weight_decay: 1e-4
  betas: [0.5, 0.9]
  # scheduler
  patience: 3
  factor: 0.1
  monitor: "val/rec_loss"
loss:
  crop_loss_weight: 0.0
model:
  module_path: nowcasting.models.ldcast.models.autoenc.autoenc.AutoencoderKL
  checkpoint_path: null
  compile: true

  enc_params: 
    in_dim: 1
    levels: 2
    min_ch: 64
  dec_params:
    in_dim: 1
    levels: 2
    min_ch: 64
  kl_weight: 0.01
  encoded_channels: 64
  hidden_width: 32

eval:
  model_name: "earthformer"
  num_samples: 32000